name: Unit Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build dev image
        run: make build.develop
      - name: Run lint
        run: ./scripts/develop.sh make fmt
      - name: Run unit test
        run: ./scripts/develop.sh make test
